# Generated by Django 3.0.8 on 2020-07-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerorderdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=30)),
                ('city', models.CharField(default='Mumbai', max_length=30)),
                ('quantity', models.IntegerField()),
                ('orderid', models.CharField(max_length=100)),
            ],
        ),
    ]
