# Generated by Django 3.0.8 on 2020-07-07 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customerorderdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderdetails',
            name='orderid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.meatproductcategories'),
        ),
    ]
