# Generated by Django 3.0.8 on 2020-07-07 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200707_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderdetails',
            name='orderid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.product'),
        ),
    ]
