# Generated by Django 3.0.8 on 2020-07-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200710_1240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='cartt',
        ),
    ]
