# Generated by Django 3.0.8 on 2020-07-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200711_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorderdetails',
            old_name='price',
            new_name='totalamount',
        ),
    ]
