# Generated by Django 3.0.8 on 2020-07-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200711_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderdetails',
            name='sid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
