# Generated by Django 3.0.8 on 2020-07-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_customerorderdetails_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderdetails',
            name='sid',
            field=models.BigIntegerField(),
        ),
    ]
