# Generated by Django 3.0.8 on 2020-07-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200711_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorderdetails',
            name='orderid',
        ),
    ]
