# Generated by Django 3.0.8 on 2020-08-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_customerorderdetails_orderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='cost_price',
        ),
        migrations.AddField(
            model_name='product',
            name='seling_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
