# Generated by Django 3.0.8 on 2020-08-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200807_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seling_price',
            new_name='price',
        ),
    ]
